parameters:
    twig.extension.readable_enum_value.class: Fresh\DoctrineEnumBundle\Twig\Extension\ReadableEnumValueExtension
    twig.extension.enum_constant.class: Fresh\DoctrineEnumBundle\Twig\Extension\EnumConstantExtension
    enum_type_guesser.class: Fresh\DoctrineEnumBundle\Form\EnumTypeGuesser

services:
    twig.extension.readable_enum_value:
        class: %twig.extension.readable_enum_value.class%
        arguments:
            - %doctrine.dbal.connection_factory.types%
        tags:
            - { name: twig.extension }

    twig.extension.enum_constant:
        class: %twig.extension.enum_constant.class%
        arguments:
            - %doctrine.dbal.connection_factory.types%
        tags:
            - { name: twig.extension }

    enum_type_guesser:
        class: %enum_type_guesser.class%
        arguments:
            - @doctrine
            - %doctrine.dbal.connection_factory.types%
        tags:
            - { name: form.type_guesser }
