language: php

sudo: false

php:
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION=4.0.*

before_install:
  - composer self-update
  - composer require --no-update symfony/symfony "$SYMFONY_VERSION"

install:
  - composer install --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpcs ./ -p --encoding=utf-8 --extensions=php --ignore="vendor|Tests" --standard=./vendor/escapestudios/symfony2-coding-standard/Symfony
  - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $COMPOSER_CACHE_DIR

notifications:
  email:
    - genvaldartem@gmail.com
